name: Block Invalid PRs

on:
  pull_request:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check PR Content
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/workflows/scripts/pr-filter.js');
            await script({ github, context });
